In [ ]:
import os
os.chdir("C:\\Users\\Lenovo\\Desktop\\New folder\\LetsUpgrade_Python_Aug\\DT")
os.getcwd()

'C:\\Users\\Lenovo\\Desktop\\New folder\\LetsUpgrade_Python_Aug\\DT'

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
daib = pd.read_csv("M4_Diabetes.csv")
daib.head(20)

No.of_times_pregnant  glucose_conc  blood_pressure  skin_fold_thickness  \
0                       6           148              72                   35   
1                       1            85              66                   29   
2                       8           183              64                    0   
3                       1            89              66                   23   
4                       0           137              40                   35   
5                       5           116              74                    0   
6                       3            78              50                   32   
7                      10           115               0                    0   
8                       2           197              70                   45   
9                       8           125              96                    0   
10                      4           110              92                    0   
11                     10           168              74                    0   
12                     10           139              80                    0   
13                      1           189              60                   23   
14                      5           166              72                   19   
15                      7           100               0                    0   
16                      0           118              84                   47   
17                      7           107              74                    0   
18                      1           103              30                   38   
19                      1           115              70                   30   

    2-Hour_serum_insulin   BMI  Diabetes_pedigree_fn  Age Is_Diabetic  
0                      0  33.6                 0.627   50         YES  
1                      0  26.6                 0.351   31          NO  
2                      0  23.3                 0.672   32         YES  
3                     94  28.1                 0.167   21          NO  
4                    168  43.1                 2.288   33         YES  
5                      0  25.6                 0.201   30          NO  
6                     88  31.0                 0.248   26         YES  
7                      0  35.3                 0.134   29          NO  
8                    543  30.5                 0.158   53         YES  
9                      0   0.0                 0.232   54         YES  
10                     0  37.6                 0.191   30          NO  
11                     0  38.0                 0.537   34         YES  
12                     0  27.1                 1.441   57          NO  
13                   846  30.1                 0.398   59         YES  
14                   175  25.8                 0.587   51         YES  
15                     0  30.0                 0.484   32         YES  
16                   230  45.8                 0.551   31         YES  
17                     0  29.6                 0.254   31         YES  
18                    83  43.3                 0.183   33          NO  
19                    96  34.6                 0.529   32         YES

In [ ]:
daib.isnull().sum()

 No.of_times_pregnant    0
glucose_conc             0
blood_pressure           0
skin_fold_thickness      0
2-Hour_serum_insulin     0
BMI                      0
Diabetes_pedigree_fn     0
Age                      0
Is_Diabetic              0
dtype: int64

In [ ]:
daib['Is_Diabetic'] = daib['Is_Diabetic'].astype("category")
daib['Is_Diabetic'] = daib['Is_Diabetic'].cat.codes
daib.head(10)

No.of_times_pregnant  glucose_conc  blood_pressure  skin_fold_thickness  \
0                      6           148              72                   35   
1                      1            85              66                   29   
2                      8           183              64                    0   
3                      1            89              66                   23   
4                      0           137              40                   35   
5                      5           116              74                    0   
6                      3            78              50                   32   
7                     10           115               0                    0   
8                      2           197              70                   45   
9                      8           125              96                    0   

   2-Hour_serum_insulin   BMI  Diabetes_pedigree_fn  Age  Is_Diabetic  
0                     0  33.6                 0.627   50            1  
1                     0  26.6                 0.351   31            0  
2                     0  23.3                 0.672   32            1  
3                    94  28.1                 0.167   21            0  
4                   168  43.1                 2.288   33            1  
5                     0  25.6                 0.201   30            0  
6                    88  31.0                 0.248   26            1  
7                     0  35.3                 0.134   29            0  
8                   543  30.5                 0.158   53            1  
9                     0   0.0                 0.232   54            1

In [ ]:
daib.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0    No.of_times_pregnant  768 non-null    int64  
 1   glucose_conc           768 non-null    int64  
 2   blood_pressure         768 non-null    int64  
 3   skin_fold_thickness    768 non-null    int64  
 4   2-Hour_serum_insulin   768 non-null    int64  
 5   BMI                    768 non-null    float64
 6   Diabetes_pedigree_fn   768 non-null    float64
 7   Age                    768 non-null    int64  
 8   Is_Diabetic            768 non-null    int8   
dtypes: float64(2), int64(6), int8(1)
memory usage: 48.9 KB


In [ ]:
daib['Is_Diabetic'].value_counts()

0    500
1    268
Name: Is_Diabetic, dtype: int64

In [ ]:
x = daib.iloc[:,0:8]
y = daib.iloc[:,8]

print(x)
print(y)

      No.of_times_pregnant  glucose_conc  blood_pressure  skin_fold_thickness  \
0                        6           148              72                   35   
1                        1            85              66                   29   
2                        8           183              64                    0   
3                        1            89              66                   23   
4                        0           137              40                   35   
..                     ...           ...             ...                  ...   
763                     10           101              76                   48   
764                      2           122              70                   27   
765                      5           121              72                   23   
766                      1           126              60                    0   
767                      1            93              70                   31   

     2-Hour_serum_insulin  

In [ ]:
# Splitting the data into training and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


In [ ]:
# Bagging concept
from sklearn.ensemble import BaggingClassifier
bag_model = BaggingClassifier()
bag_model.fit(x_train, y_train)

BaggingClassifier()

In [ ]:
y_pred_bag_train = bag_model.predict(x_train)
y_pred_bag_test = bag_model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print(accuracy_score(y_train,y_pred_bag_train))
print(accuracy_score(y_test,y_pred_bag_test))

0.9809027777777778
0.7552083333333334


In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred_rf_train = rf.predict(x_train)
y_pred_rf_test = rf.predict(x_test)

In [ ]:
print(accuracy_score(y_train,y_pred_rf_train))
print(accuracy_score(y_test,y_pred_rf_test))

1.0
0.765625


In [ ]:
# Cross Validation Method
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator=bag_model, X=x_train, y=y_train, cv=15)
accuracy

array([0.71794872, 0.66666667, 0.76923077, 0.66666667, 0.76923077,
       0.87179487, 0.65789474, 0.84210526, 0.78947368, 0.76315789,
       0.68421053, 0.65789474, 0.81578947, 0.71052632, 0.73684211])

In [ ]:
accuracy[5]

0.8717948717948718

In [ ]:
# Cross Validation Method
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator=rf, X=x_train, y=y_train, cv=20)
accuracy

array([0.79310345, 0.68965517, 0.75862069, 0.75862069, 0.65517241,
       0.75862069, 0.75862069, 0.79310345, 0.62068966, 0.68965517,
       0.96551724, 0.79310345, 0.75862069, 0.51724138, 0.75862069,
       0.55172414, 0.78571429, 0.78571429, 0.75      , 0.89285714])

In [ ]:
accuracy[10]

0.9655172413793104

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred_lr_train = lr.predict(x_train)
y_pred_lr_test = lr.predict(x_test)

In [ ]:
print(accuracy_score(y_train,y_pred_lr_train))
print(accuracy_score(y_test,y_pred_lr_test ))

0.7708333333333334
0.7916666666666666


In [ ]:
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator=lr, X=x_train, y=y_train, cv=20)
accuracy

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

array([0.82758621, 0.72413793, 0.79310345, 0.86206897, 0.79310345,
       0.75862069, 0.75862069, 0.79310345, 0.68965517, 0.75862069,
       0.86206897, 0.72413793, 0.68965517, 0.5862069 , 0.72413793,
       0.5862069 , 0.82142857, 0.78571429, 0.71428571, 0.85714286])