In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
datasets = pd.read_csv('women.csv')

In [4]:
datasets.head()

height  weight
0      58     115
1      59     117
2      60     120
3      61     123
4      62     126

In [5]:

datasets.shape

(15, 2)

In [6]:
datasets.corr()

height    weight
height  1.000000  0.995495
weight  0.995495  1.000000

In [7]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  15 non-null     int64
 1   weight  15 non-null     int64
dtypes: int64(2)
memory usage: 368.0 bytes


In [8]:
datasets.describe()

height      weight
count  15.000000   15.000000
mean   65.000000  136.733333
std     4.472136   15.498694
min    58.000000  115.000000
25%    61.500000  124.500000
50%    65.000000  135.000000
75%    68.500000  148.000000
max    72.000000  164.000000

In [9]:
datasets

height  weight
0       58     115
1       59     117
2       60     120
3       61     123
4       62     126
5       63     129
6       64     132
7       65     135
8       66     139
9       67     142
10      68     146
11      69     150
12      70     154
13      71     159
14      72     164

In [22]:
x=np.array(datasets['height'])
y=np.array(datasets['weight'])

In [19]:
x

array([58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72])

In [20]:
y

array([115, 117, 120, 123, 126, 129, 132, 135, 139, 142, 146, 150, 154,
       159, 164])

In [24]:
from sklearn.model_selection import train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split(x,y, test_size = 1/3, random_state = 0)

In [25]:
X_Test

array([59, 64, 66, 67, 72])

In [26]:
X_Train

array([62, 60, 71, 68, 65, 69, 61, 58, 63, 70])

In [27]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
print(regressor)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)


In [28]:
regressor.fit(X_Train, Y_Train)

ValueError: Expected 2D array, got 1D array instead:
array=[62 60 71 68 65 69 61 58 63 70].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.