In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
a

array([1, 2, 3], dtype=int32)

In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
a.ndim      #gives the no of Rows

1

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [13]:
a.itemsize

4

In [14]:
a.nbytes


12

In [15]:
a.size

3

In [16]:
b.size

6

In [18]:
b.itemsize   //ndim + size

8

In [19]:
b.nbytes

48

In [21]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
x[0,4]

5

In [24]:
x[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
x[:,0]

array([1, 8])

In [26]:
x[:,4]

array([ 5, 12])

In [27]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
c.shape

(2, 2, 2)

In [29]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]], [[9,10],[11,12]]])
print(d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [31]:
d.shape

(3, 2, 2)

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [34]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [35]:
np.ones((4,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [37]:
np.full((3,3,3), 699)

array([[[699, 699, 699],
        [699, 699, 699],
        [699, 699, 699]],

       [[699, 699, 699],
        [699, 699, 699],
        [699, 699, 699]],

       [[699, 699, 699],
        [699, 699, 699],
        [699, 699, 699]]])

In [41]:
np.random.rand(2,2)

array([[0.06846081, 0.44101582],
       [0.41552377, 0.29119999]])

In [42]:
np.random.randint(-2,2, size=(3,3))

array([[-1,  0, -2],
       [ 0,  0, -2],
       [ 0, -2, -2]])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.min(stats)

1

In [47]:
np.mean(stats)

3.5

In [48]:
np.median(stats)

3.5

In [49]:
np.mode(stats)    // mode is not available in numpy it is available in pandas

AttributeError: module 'numpy' has no attribute 'mode'

In [50]:
np.sum(stats)

21

In [51]:
np.std(stats)

1.707825127659933

In [52]:
np.var(stats)

2.9166666666666665

In [53]:
np.skew(stats)   // IN PANDAS

AttributeError: module 'numpy' has no attribute 'skew'

In [55]:
np.kurt(stats) // In Pandas

AttributeError: module 'numpy' has no attribute 'kurt'