In [1]:
import os
os.chdir("C:\\Users\\Lenovo\\Desktop\\New folder\\LetsUpgrade_Python_Aug\\New folder")

In [2]:
os.getcwd()

'C:\\Users\\Lenovo\\Desktop\\New folder\\LetsUpgrade_Python_Aug\\New folder'

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
dataset = pd.read_csv("Bank-data.csv")
dataset.head()

Index  interest_rate  credit  Gender  previous  duration Churn
0      0          1.334       0       1         0       117    no
1      1          0.767       0       0         1       274   yes
2      2          4.858       0       1         0       167    no
3      3          4.120       0       0         0       686   yes
4      4          4.856       0       1         0       159    no

In [6]:
dataset['Churn'] = dataset['Churn'].astype("category")
dataset['Churn'] = dataset['Churn'].cat.codes
dataset.head()

Index  interest_rate  credit  Gender  previous  duration  Churn
0      0          1.334       0       1         0       117      0
1      1          0.767       0       0         1       274      1
2      2          4.858       0       1         0       167      0
3      3          4.120       0       0         0       686      1
4      4          4.856       0       1         0       159      0

In [19]:
dataset['Churn'].value_counts()

0    259
1    259
Name: Churn, dtype: int64

In [11]:
# split
x = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [12]:
x

array([[  0.   ,   1.334,   0.   ,   1.   ,   0.   , 117.   ],
       [  1.   ,   0.767,   0.   ,   0.   ,   1.   , 274.   ],
       [  2.   ,   4.858,   0.   ,   1.   ,   0.   , 167.   ],
       ...,
       [515.   ,   0.879,   0.   ,   0.   ,   0.   , 290.   ],
       [516.   ,   0.877,   0.   ,   0.   ,   1.   , 473.   ],
       [517.   ,   4.965,   0.   ,   0.   ,   0.   , 142.   ]])

In [22]:
# splitting the data into training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.75, random_state=0)

In [23]:
# Building Logistic Regression
from sklearn.linear_model import LogisticRegression

In [24]:
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
y_pred = logmodel.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
print(confusion_matrix(y_test, y_pred))\

print(accuracy_score(y_test, y_pred))

[[50  6]
 [ 6 68]]
0.9076923076923077


In [ ]:
# Logistic Regression Accuracy - 90.7%

# Principal Component Analysis

In [28]:
from sklearn.decomposition import PCA

In [29]:
pca = PCA(n_components=None, random_state=0) # None - all componant / variables/values 
# none - by default system will provide the slice count
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [30]:
x_train_n
[-1.67553840e+02  3.00085255e+01]
 [ 7.63378005e+02 -8.83590844e+01]
 [-1.13805701e+02 -1.62478256e+02]
 [-6.76035804e+01  1.34024675e+02]
 [-2.07544391e+02 -2.06285294e+02

array([[-1.67553840e+02,  3.00085255e+01, -1.85861703e+00,
         7.50564150e-01,  7.10405793e-02,  1.33259721e-02],
       [ 7.63378005e+02, -8.83590844e+01, -1.78641888e+00,
         7.92873992e-01,  3.86292382e-02,  3.24104871e-02],
       [-1.13805701e+02, -1.62478256e+02, -2.09455718e+00,
        -2.10164934e-01, -2.31985076e-02,  3.06919432e-03],
       ...,
       [ 1.79376803e+01,  2.51622623e+02, -1.71327916e+00,
        -2.79018021e-01,  9.90571355e-03, -4.08756002e-02],
       [-2.79518147e+02, -1.07384792e+02,  2.21686297e+00,
        -3.48750596e-01,  6.98273354e-01, -1.08981275e-01],
       [-2.93480498e+02,  5.92743272e+01,  1.71904778e+00,
         7.03321544e-01, -1.59605681e-01, -1.79221660e-02]])

In [31]:
x_test_n 

array([[ 2.44017584e+02, -1.22259730e+02,  2.44650098e+00,
         6.21440201e-01,  2.43503357e-01,  7.26630996e-02],
       [-2.02043239e+02, -1.38878091e+02, -2.09841289e+00,
        -1.22592045e-01, -3.73295234e-01, -1.63657204e-01],
       [-8.60570636e+01, -4.45813004e+01, -9.24561045e-01,
        -2.53915380e-01, -3.47866358e-01,  8.77636083e-01],
       [ 2.29944932e+02, -2.57661672e+00, -1.74639925e+00,
        -2.10623342e-01, -3.34632579e-01, -1.23426783e-01],
       [-1.15434534e+02, -7.73973331e+01, -1.90873974e+00,
        -4.18269516e-01,  6.02885699e-01, -1.16382515e-01],
       [-1.47887099e+02, -2.33191759e+02, -1.45553937e+00,
        -1.59658905e-01, -3.16835607e-01, -1.54789701e-01],
       [-2.59222734e+02,  2.21785774e+02,  2.13884893e+00,
        -1.90250115e-01, -1.10490177e-01, -1.24532188e-02],
       [ 5.74327597e+02, -4.88184558e+01,  1.93525486e+00,
        -3.85201060e-01, -5.18314208e-02, -1.71323356e-02],
       [-2.15685506e+02,  1.36918179e+02,  2.165

In [32]:
x_test

array([[1.420e+02, 4.855e+00, 0.000e+00, 1.000e+00, 0.000e+00, 6.530e+02],
       [1.070e+02, 7.230e-01, 0.000e+00, 0.000e+00, 0.000e+00, 2.080e+02],
       [2.060e+02, 1.799e+00, 1.000e+00, 0.000e+00, 0.000e+00, 3.200e+02],
       [2.610e+02, 6.440e-01, 0.000e+00, 0.000e+00, 0.000e+00, 6.340e+02],
       [1.720e+02, 8.960e-01, 0.000e+00, 0.000e+00, 1.000e+00, 2.920e+02],
       [1.500e+01, 1.334e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.660e+02],
       [4.650e+02, 4.962e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.360e+02],
       [2.290e+02, 4.021e+00, 0.000e+00, 0.000e+00, 0.000e+00, 9.800e+02],
       [3.820e+02, 4.963e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.830e+02],
       [9.700e+01, 4.962e+00, 0.000e+00, 0.000e+00, 0.000e+00, 5.900e+01],
       [3.850e+02, 4.153e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.800e+02],
       [2.450e+02, 1.250e+00, 0.000e+00, 1.000e+00, 0.000e+00, 1.357e+03],
       [1.530e+02, 1.299e+00, 0.000e+00, 1.000e+00, 0.000e+00, 6.890e+02],
       [4.410e+02, 4.966e

In [33]:
print(pd.DataFrame(x_train))
print(pd.DataFrame(x_train_n))

         0      1    2    3    4       5
0    225.0  4.857  0.0  1.0  0.0   211.0
1    371.0  4.856  0.0  1.0  0.0  1138.0
2    419.0  4.963  0.0  0.0  0.0   259.0
3    124.0  1.291  0.0  1.0  0.0   314.0
4    460.0  4.957  0.0  0.0  0.0   164.0
..     ...    ...  ...  ...  ...     ...
383   70.0  4.970  0.0  0.0  0.0    39.0
384  277.0  1.264  0.0  1.0  0.0   143.0
385    9.0  4.865  0.0  0.0  0.0   403.0
386  359.0  0.715  0.0  0.0  1.0    95.0
387  192.0  1.270  0.0  1.0  0.0    86.0

[388 rows x 6 columns]
              0           1         2         3         4         5
0   -167.553840   30.008525 -1.858617  0.750564  0.071041  0.013326
1    763.378005  -88.359084 -1.786419  0.792874  0.038629  0.032410
2   -113.805701 -162.478256 -2.094557 -0.210165 -0.023199  0.003069
3    -67.603580  134.024675  1.781035  0.696104 -0.155470 -0.024154
4   -207.544391 -206.285294 -2.131104 -0.204951 -0.026046  0.007038
..          ...         ...       ...       ...       ...       ...
383 -344

In [34]:
# This is the crux of PCA to identify how many split happen after using PCA 

explained_variance = pca.explained_variance_ratio_

In [35]:
explained_variance

array([8.50574681e-01, 1.49399073e-01, 2.36710907e-05, 1.45054374e-06,
       7.84073269e-07, 3.40130686e-07])

In [ ]:
# PCA1 - 0.850574681
# PCA2 - 0.149399073

# PCA3 - 0.00002367109 
# PCA4 - 
# PCA5 - 
# PCA6 - 

In [36]:
# PCA : n_components = 2
pca = PCA(n_components=2, random_state=0) # None - all componant / variables/values 
# none - by default system will provide the slice count
x_train_2 = pca.fit_transform(x_train)
x_test_2 = pca.fit_transform(x_test)

In [39]:
print(x_train_2)


[[-1.67553840e+02  3.00085255e+01]
 [ 7.63378005e+02 -8.83590844e+01]
 [-1.13805701e+02 -1.62478256e+02]
 [-6.76035804e+01  1.34024675e+02]
 [-2.07544391e+02 -2.06285294e+02]
 [-2.35570315e+01  2.00363345e+02]
 [-5.63761540e+00  6.88386597e+01]
 [ 2.08812927e+02 -1.44878532e+02]
 [ 3.15464922e+01 -1.72160010e+02]
 [-1.65986524e+02 -2.58074416e+02]
 [-2.50281466e+02 -1.48533161e+02]
 [ 2.37091281e+02 -2.21071642e+02]
 [-5.56618327e+01  2.03409936e+02]
 [-2.80997857e+02  9.62583682e+00]
 [ 1.09005880e+02 -1.52850115e+02]
 [-2.23211811e+02  2.19436918e+02]
 [ 3.63181002e+02  4.67971334e+01]
 [-1.19991414e+02  4.54297888e+01]
 [-1.22931213e+02  4.33387986e+01]
 [ 1.42564038e+03  1.14425300e+02]
 [-2.96643766e+02  1.99244282e+02]
 [-1.91126983e+01  1.85488983e+02]
 [-1.18496148e+02  2.30556004e+02]
 [-1.69999638e+02  4.49397644e+01]
 [-2.26103116e+02  2.49364315e+02]
 [ 9.43138175e+02 -4.39937276e+01]
 [-3.78217010e+01 -1.27205217e+02]
 [-3.14550530e+02 -1.40440543e+02]
 [-2.65056728e+02  2

In [40]:
# Logistic Regression with PCA method
logmodel_pca = LogisticRegression()
logmodel_pca.fit(x_train_2, y_train)

LogisticRegression()

In [41]:
y_pred_pca = logmodel_pca.predict(x_test_2)

In [42]:
accuracy_score(y_test, y_pred_pca)

0.6538461538461539

In [62]:
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator=logmodel_pca, X = x_train_2, y = y_train, cv=10)
accuracy

array([0.76923077, 0.64102564, 0.69230769, 0.53846154, 0.71794872,
       0.79487179, 0.74358974, 0.79487179, 0.65789474, 0.71052632])

In [63]:
accuracy[5]

0.7948717948717948

In [47]:
# RandomForest 

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=5000,criterion='gini')
rf.fit(x_train_2, y_train)

RandomForestClassifier(n_estimators=5000)

In [48]:
rf_pred = rf.predict(x_test_2)

In [49]:
accuracy_score(y_test, rf_pred)

0.6461538461538462

In [57]:
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator=rf, X = x_train_2, y = y_train, cv=10)
accuracy

0.717948717948718

In [59]:
accuracy[6]

0.7435897435897436

In [51]:
# XGBoosting 

from xgboost import XGBClassifier

In [52]:
xgb = XGBClassifier()
xgb.fit(x_train_2, y_train)

[21:23:15] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [53]:
xgb_pred = xgb.predict(x_test_2)

In [54]:
accuracy_score(y_test, xgb_pred)

0.6230769230769231

In [60]:
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator=xgb, X = x_train_2, y = y_train, cv=10)
accuracy

C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:32:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[21:32:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:32:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[21:32:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:32:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[21:32:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:32:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[21:32:53] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:32:53] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Lenovo\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:32:53] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


array([0.71794872, 0.69230769, 0.64102564, 0.61538462, 0.66666667,
       0.51282051, 0.64102564, 0.66666667, 0.63157895, 0.65789474])

In [61]:
accuracy[0]

0.717948717948718